service: IamAccessKeysExpirator

provider:
  stage: prod
  name: aws
  region: eu-central-1
  runtime: nodejs14.x

  memorySize: 128
  logRetentionInDays: 90

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - iam:DeleteAccessKey
            - iam:ListAccessKeys
            - iam:ListUsers
            - iam:GetUser
          Resource: "*"

        - Effect: Allow
          Action:
            - ses:SendEmail
          Resource: "*"

functions:
  checkKeysOfUsers:
    handler: src/index.handler
    events:
      - schedule:
          rate: cron(0 8 * * ? *)
    environment:
      DEFAULT_TO_EMAIL: my@example.com
      FROM_EMAIL: iam-access-keys-expirator@example.com
    timeout: 300